# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_save.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_save(object):
    def setupUi(self, Dialog_save):
        Dialog_save.setObjectName("Dialog_save")
        Dialog_save.resize(513, 120)
        Dialog_save.setMinimumSize(QtCore.QSize(0, 120))
        Dialog_save.setMaximumSize(QtCore.QSize(16777215, 120))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_save)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_path = QtWidgets.QLabel(Dialog_save)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_path.setFont(font)
        self.label_path.setObjectName("label_path")
        self.gridLayout.addWidget(self.label_path, 0, 0, 1, 1)
        self.path_text = QtWidgets.QLineEdit(Dialog_save)
        self.path_text.setMinimumSize(QtCore.QSize(0, 0))
        self.path_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.path_text.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.path_text.setText("")
        self.path_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.path_text.setObjectName("path_text")
        self.gridLayout.addWidget(self.path_text, 0, 1, 1, 1)
        self.btn_browse = QtWidgets.QPushButton(Dialog_save)
        self.btn_browse.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_browse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_browse.setObjectName("btn_browse")
        self.gridLayout.addWidget(self.btn_browse, 0, 2, 1, 1)
        self.label_exp_name = QtWidgets.QLabel(Dialog_save)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_exp_name.setFont(font)
        self.label_exp_name.setObjectName("label_exp_name")
        self.gridLayout.addWidget(self.label_exp_name, 1, 0, 1, 1)
        self.exp_name_text = QtWidgets.QLineEdit(Dialog_save)
        self.exp_name_text.setMinimumSize(QtCore.QSize(0, 0))
        self.exp_name_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.exp_name_text.setText("")
        self.exp_name_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.exp_name_text.setObjectName("exp_name_text")
        self.gridLayout.addWidget(self.exp_name_text, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_save = QtWidgets.QPushButton(Dialog_save)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(Dialog_save)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog_save)
        QtCore.QMetaObject.connectSlotsByName(Dialog_save)

    def retranslateUi(self, Dialog_save):
        _translate = QtCore.QCoreApplication.translate
        Dialog_save.setWindowTitle(_translate("Dialog_save", "Save Golgi mini-stacks"))
        self.label_path.setText(_translate("Dialog_save", "Path"))
        self.btn_browse.setText(_translate("Dialog_save", "Browse"))
        self.label_exp_name.setText(_translate("Dialog_save", "Exp. name"))
        self.btn_save.setText(_translate("Dialog_save", "Save"))
        self.btn_cancel.setText(_translate("Dialog_save", "Cancel"))
